version: "3.1"

services:
  plutus-ui:
    build: .
    environment: 
     - "API_PATH=http://47.56.69.103/api/v1/address/"
    command: ["npm", "run", "serve"]
    ports:
      - "0.0.0.0:80:3000"
    volumes:
    #  - ./node_modules:/app/node_modules
     - ./src:/app/src
    restart: always
    # networks:
    #   - plutusnetwork

networks:
  default:
    external:
      name: front_default